// Generated by https://quicktype.io

export interface AssetDetail {
   pkAssetHistoryDetailId: number;
   fkAssetId:              FkAssetID;
   timeOfTracking:         string;
   latitude:               number;
   longitude:              number;
}

export interface FkAssetID {
   pkAssetId:          number;
   fkAssetType:        FkAssetType;
   assetName:          string;
   assetContactDetail: number;
}

export interface FkAssetType {
   pkAssetTypeId: number;
   assetType:     string;
}

// Generated by https://quicktype.io

export interface Coordinates {
   lat: number;
   lng: number;
}

